/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R3dMaxHelpRouteImport } from './routes/3d-max-help'
import { Route as R3dModellingHelpRouteImport } from './routes/3d-modelling-help'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AbuDhabiAcademicSupportRouteImport } from './routes/abu-dhabi-academic-support'
import { Route as AcademicWritingCoachingRouteImport } from './routes/academic-writing-coaching'
import { Route as ArchitectureMaquetteHelpRouteImport } from './routes/architecture-maquette-help'
import { Route as ArchitectureProjectHelpRouteImport } from './routes/architecture-project-help'
import { Route as ArduinoProjectHelpRouteImport } from './routes/arduino-project-help'
import { Route as ArtsHumanitiesAcademicSupportRouteImport } from './routes/arts-humanities-academic-support'
import { Route as AssignmentCourseworkGuidanceRouteImport } from './routes/assignment-coursework-guidance'
import { Route as AutocadHelpRouteImport } from './routes/autocad-help'
import { Route as BuildingModelHelpRouteImport } from './routes/building-model-help'
import { Route as BusinessAcademicSupportRouteImport } from './routes/business-academic-support'
import { Route as CapstoneProjectSupportRouteImport } from './routes/capstone-project-support'
import { Route as ComputerScienceAcademicSupportRouteImport } from './routes/computer-science-academic-support'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DataAnalysisStatisticsRouteImport } from './routes/data-analysis-statistics'
import { Route as DesignAcademicSupportRouteImport } from './routes/design-academic-support'
import { Route as DubaiAcademicSupportRouteImport } from './routes/dubai-academic-support'
import { Route as EngineeringProjectHelpRouteImport } from './routes/engineering-project-help'
import { Route as EngineeringSoftwareSupportRouteImport } from './routes/engineering-software-support'
import { Route as FinalYearProjectSupportRouteImport } from './routes/final-year-project-support'
import { Route as GisProjectHelpRouteImport } from './routes/gis-project-help'
import { Route as InternationalStudentAcademicSupportRouteImport } from './routes/international-student-academic-support'
import { Route as LawAcademicSupportRouteImport } from './routes/law-academic-support'
import { Route as LebanonAcademicSupportRouteImport } from './routes/lebanon-academic-support'
import { Route as LiteratureReviewSupportRouteImport } from './routes/literature-review-support'
import { Route as MedicineAcademicSupportRouteImport } from './routes/medicine-academic-support'
import { Route as MontrealAcademicSupportRouteImport } from './routes/montreal-academic-support'
import { Route as PhdResearchSupportRouteImport } from './routes/phd-research-support'
import { Route as PhotoshopAcademicProjectHelpRouteImport } from './routes/photoshop-academic-project-help'
import { Route as PhysicalProjectModelsRouteImport } from './routes/physical-project-models'
import { Route as ResearchMethodologySupportRouteImport } from './routes/research-methodology-support'
import { Route as ResearchProposalSupportRouteImport } from './routes/research-proposal-support'
import { Route as RevitProjectHelpRouteImport } from './routes/revit-project-help'
import { Route as ScienceAcademicSupportRouteImport } from './routes/science-academic-support'
import { Route as SocialScienceAcademicSupportRouteImport } from './routes/social-science-academic-support'
import { Route as SpssStatisticsHelpRouteImport } from './routes/spss-statistics-help'
import { Route as ThesisDissertationCoachingRouteImport } from './routes/thesis-dissertation-coaching'
import { Route as UkAcademicSupportRouteImport } from './routes/uk-academic-support'
import { Route as WhoWeHelpRouteImport } from './routes/who-we-help'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsAbuDhabiRouteImport } from './routes/locations/abu-dhabi'
import { Route as LocationsDubaiRouteImport } from './routes/locations/dubai'
import { Route as LocationsLebanonRouteImport } from './routes/locations/lebanon'
import { Route as LocationsMontrealRouteImport } from './routes/locations/montreal'
import { Route as LocationsUkRouteImport } from './routes/locations/uk'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesArchitectureMaquetteGuideRouteImport } from './routes/resources/architecture-maquette-guide'
import { Route as ResourcesEngineeringFinalYearProjectGuideRouteImport } from './routes/resources/engineering-final-year-project-guide'
import { Route as ResourcesHowToChooseDissertationMethodologyRouteImport } from './routes/resources/how-to-choose-dissertation-methodology'
import { Route as ResourcesRevitForArchitectureStudentsRouteImport } from './routes/resources/revit-for-architecture-students'
import { Route as ResourcesSpssDissertationDataAnalysisGuideRouteImport } from './routes/resources/spss-dissertation-data-analysis-guide'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAcademicCoachingRouteImport } from './routes/services/academic-coaching'
import { Route as ServicesAcademicWritingCoachingRouteImport } from './routes/services/academic-writing-coaching'
import { Route as ServicesEditingProofreadingRouteImport } from './routes/services/editing-proofreading'
import { Route as ServicesExamPreparationRouteImport } from './routes/services/exam-preparation'
import { Route as ServicesResearchMethodologyRouteImport } from './routes/services/research-methodology'
import { Route as ServicesResearchStatisticsSupportRouteImport } from './routes/services/research-statistics-support'
import { Route as ServicesSatPreparationRouteImport } from './routes/services/sat-preparation'
import { Route as ServicesThesisDissertationCoachingRouteImport } from './routes/services/thesis-dissertation-coaching'
import { Route as ServicesUniversityTutoringRouteImport } from './routes/services/university-tutoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dMaxHelpRoute = R3dMaxHelpRouteImport.update({
  id: '/3d-max-help',
  path: '/3d-max-help',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dModellingHelpRoute = R3dModellingHelpRouteImport.update({
  id: '/3d-modelling-help',
  path: '/3d-modelling-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AbuDhabiAcademicSupportRoute = AbuDhabiAcademicSupportRouteImport.update({
  id: '/abu-dhabi-academic-support',
  path: '/abu-dhabi-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicWritingCoachingRoute = AcademicWritingCoachingRouteImport.update({
  id: '/academic-writing-coaching',
  path: '/academic-writing-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureMaquetteHelpRoute =
  ArchitectureMaquetteHelpRouteImport.update({
    id: '/architecture-maquette-help',
    path: '/architecture-maquette-help',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchitectureProjectHelpRoute = ArchitectureProjectHelpRouteImport.update({
  id: '/architecture-project-help',
  path: '/architecture-project-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ArduinoProjectHelpRoute = ArduinoProjectHelpRouteImport.update({
  id: '/arduino-project-help',
  path: '/arduino-project-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtsHumanitiesAcademicSupportRoute =
  ArtsHumanitiesAcademicSupportRouteImport.update({
    id: '/arts-humanities-academic-support',
    path: '/arts-humanities-academic-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssignmentCourseworkGuidanceRoute =
  AssignmentCourseworkGuidanceRouteImport.update({
    id: '/assignment-coursework-guidance',
    path: '/assignment-coursework-guidance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutocadHelpRoute = AutocadHelpRouteImport.update({
  id: '/autocad-help',
  path: '/autocad-help',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingModelHelpRoute = BuildingModelHelpRouteImport.update({
  id: '/building-model-help',
  path: '/building-model-help',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAcademicSupportRoute = BusinessAcademicSupportRouteImport.update({
  id: '/business-academic-support',
  path: '/business-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const CapstoneProjectSupportRoute = CapstoneProjectSupportRouteImport.update({
  id: '/capstone-project-support',
  path: '/capstone-project-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerScienceAcademicSupportRoute =
  ComputerScienceAcademicSupportRouteImport.update({
    id: '/computer-science-academic-support',
    path: '/computer-science-academic-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAnalysisStatisticsRoute = DataAnalysisStatisticsRouteImport.update({
  id: '/data-analysis-statistics',
  path: '/data-analysis-statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignAcademicSupportRoute = DesignAcademicSupportRouteImport.update({
  id: '/design-academic-support',
  path: '/design-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const DubaiAcademicSupportRoute = DubaiAcademicSupportRouteImport.update({
  id: '/dubai-academic-support',
  path: '/dubai-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringProjectHelpRoute = EngineeringProjectHelpRouteImport.update({
  id: '/engineering-project-help',
  path: '/engineering-project-help',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringSoftwareSupportRoute =
  EngineeringSoftwareSupportRouteImport.update({
    id: '/engineering-software-support',
    path: '/engineering-software-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinalYearProjectSupportRoute = FinalYearProjectSupportRouteImport.update({
  id: '/final-year-project-support',
  path: '/final-year-project-support',
  getParentRoute: () => rootRouteImport,
} as any)
const GisProjectHelpRoute = GisProjectHelpRouteImport.update({
  id: '/gis-project-help',
  path: '/gis-project-help',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalStudentAcademicSupportRoute =
  InternationalStudentAcademicSupportRouteImport.update({
    id: '/international-student-academic-support',
    path: '/international-student-academic-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const LawAcademicSupportRoute = LawAcademicSupportRouteImport.update({
  id: '/law-academic-support',
  path: '/law-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const LebanonAcademicSupportRoute = LebanonAcademicSupportRouteImport.update({
  id: '/lebanon-academic-support',
  path: '/lebanon-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureReviewSupportRoute = LiteratureReviewSupportRouteImport.update({
  id: '/literature-review-support',
  path: '/literature-review-support',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineAcademicSupportRoute = MedicineAcademicSupportRouteImport.update({
  id: '/medicine-academic-support',
  path: '/medicine-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const MontrealAcademicSupportRoute = MontrealAcademicSupportRouteImport.update({
  id: '/montreal-academic-support',
  path: '/montreal-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const PhdResearchSupportRoute = PhdResearchSupportRouteImport.update({
  id: '/phd-research-support',
  path: '/phd-research-support',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoshopAcademicProjectHelpRoute =
  PhotoshopAcademicProjectHelpRouteImport.update({
    id: '/photoshop-academic-project-help',
    path: '/photoshop-academic-project-help',
    getParentRoute: () => rootRouteImport,
  } as any)
const PhysicalProjectModelsRoute = PhysicalProjectModelsRouteImport.update({
  id: '/physical-project-models',
  path: '/physical-project-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchMethodologySupportRoute =
  ResearchMethodologySupportRouteImport.update({
    id: '/research-methodology-support',
    path: '/research-methodology-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchProposalSupportRoute = ResearchProposalSupportRouteImport.update({
  id: '/research-proposal-support',
  path: '/research-proposal-support',
  getParentRoute: () => rootRouteImport,
} as any)
const RevitProjectHelpRoute = RevitProjectHelpRouteImport.update({
  id: '/revit-project-help',
  path: '/revit-project-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceAcademicSupportRoute = ScienceAcademicSupportRouteImport.update({
  id: '/science-academic-support',
  path: '/science-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialScienceAcademicSupportRoute =
  SocialScienceAcademicSupportRouteImport.update({
    id: '/social-science-academic-support',
    path: '/social-science-academic-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpssStatisticsHelpRoute = SpssStatisticsHelpRouteImport.update({
  id: '/spss-statistics-help',
  path: '/spss-statistics-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesisDissertationCoachingRoute =
  ThesisDissertationCoachingRouteImport.update({
    id: '/thesis-dissertation-coaching',
    path: '/thesis-dissertation-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const UkAcademicSupportRoute = UkAcademicSupportRouteImport.update({
  id: '/uk-academic-support',
  path: '/uk-academic-support',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpRoute = WhoWeHelpRouteImport.update({
  id: '/who-we-help',
  path: '/who-we-help',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsAbuDhabiRoute = LocationsAbuDhabiRouteImport.update({
  id: '/locations/abu-dhabi',
  path: '/locations/abu-dhabi',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsDubaiRoute = LocationsDubaiRouteImport.update({
  id: '/locations/dubai',
  path: '/locations/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLebanonRoute = LocationsLebanonRouteImport.update({
  id: '/locations/lebanon',
  path: '/locations/lebanon',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMontrealRoute = LocationsMontrealRouteImport.update({
  id: '/locations/montreal',
  path: '/locations/montreal',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsUkRoute = LocationsUkRouteImport.update({
  id: '/locations/uk',
  path: '/locations/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesArchitectureMaquetteGuideRoute =
  ResourcesArchitectureMaquetteGuideRouteImport.update({
    id: '/resources/architecture-maquette-guide',
    path: '/resources/architecture-maquette-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesEngineeringFinalYearProjectGuideRoute =
  ResourcesEngineeringFinalYearProjectGuideRouteImport.update({
    id: '/resources/engineering-final-year-project-guide',
    path: '/resources/engineering-final-year-project-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesHowToChooseDissertationMethodologyRoute =
  ResourcesHowToChooseDissertationMethodologyRouteImport.update({
    id: '/resources/how-to-choose-dissertation-methodology',
    path: '/resources/how-to-choose-dissertation-methodology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesRevitForArchitectureStudentsRoute =
  ResourcesRevitForArchitectureStudentsRouteImport.update({
    id: '/resources/revit-for-architecture-students',
    path: '/resources/revit-for-architecture-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesSpssDissertationDataAnalysisGuideRoute =
  ResourcesSpssDissertationDataAnalysisGuideRouteImport.update({
    id: '/resources/spss-dissertation-data-analysis-guide',
    path: '/resources/spss-dissertation-data-analysis-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAcademicCoachingRoute =
  ServicesAcademicCoachingRouteImport.update({
    id: '/services/academic-coaching',
    path: '/services/academic-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAcademicWritingCoachingRoute =
  ServicesAcademicWritingCoachingRouteImport.update({
    id: '/services/academic-writing-coaching',
    path: '/services/academic-writing-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEditingProofreadingRoute =
  ServicesEditingProofreadingRouteImport.update({
    id: '/services/editing-proofreading',
    path: '/services/editing-proofreading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesExamPreparationRoute = ServicesExamPreparationRouteImport.update({
  id: '/services/exam-preparation',
  path: '/services/exam-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResearchMethodologyRoute =
  ServicesResearchMethodologyRouteImport.update({
    id: '/services/research-methodology',
    path: '/services/research-methodology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesResearchStatisticsSupportRoute =
  ServicesResearchStatisticsSupportRouteImport.update({
    id: '/services/research-statistics-support',
    path: '/services/research-statistics-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSatPreparationRoute = ServicesSatPreparationRouteImport.update({
  id: '/services/sat-preparation',
  path: '/services/sat-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesThesisDissertationCoachingRoute =
  ServicesThesisDissertationCoachingRouteImport.update({
    id: '/services/thesis-dissertation-coaching',
    path: '/services/thesis-dissertation-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUniversityTutoringRoute =
  ServicesUniversityTutoringRouteImport.update({
    id: '/services/university-tutoring',
    path: '/services/university-tutoring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-max-help': typeof R3dMaxHelpRoute
  '/3d-modelling-help': typeof R3dModellingHelpRoute
  '/about': typeof AboutRoute
  '/abu-dhabi-academic-support': typeof AbuDhabiAcademicSupportRoute
  '/academic-writing-coaching': typeof AcademicWritingCoachingRoute
  '/architecture-maquette-help': typeof ArchitectureMaquetteHelpRoute
  '/architecture-project-help': typeof ArchitectureProjectHelpRoute
  '/arduino-project-help': typeof ArduinoProjectHelpRoute
  '/arts-humanities-academic-support': typeof ArtsHumanitiesAcademicSupportRoute
  '/assignment-coursework-guidance': typeof AssignmentCourseworkGuidanceRoute
  '/autocad-help': typeof AutocadHelpRoute
  '/building-model-help': typeof BuildingModelHelpRoute
  '/business-academic-support': typeof BusinessAcademicSupportRoute
  '/capstone-project-support': typeof CapstoneProjectSupportRoute
  '/computer-science-academic-support': typeof ComputerScienceAcademicSupportRoute
  '/contact': typeof ContactRoute
  '/data-analysis-statistics': typeof DataAnalysisStatisticsRoute
  '/design-academic-support': typeof DesignAcademicSupportRoute
  '/dubai-academic-support': typeof DubaiAcademicSupportRoute
  '/engineering-project-help': typeof EngineeringProjectHelpRoute
  '/engineering-software-support': typeof EngineeringSoftwareSupportRoute
  '/final-year-project-support': typeof FinalYearProjectSupportRoute
  '/gis-project-help': typeof GisProjectHelpRoute
  '/international-student-academic-support': typeof InternationalStudentAcademicSupportRoute
  '/law-academic-support': typeof LawAcademicSupportRoute
  '/lebanon-academic-support': typeof LebanonAcademicSupportRoute
  '/literature-review-support': typeof LiteratureReviewSupportRoute
  '/medicine-academic-support': typeof MedicineAcademicSupportRoute
  '/montreal-academic-support': typeof MontrealAcademicSupportRoute
  '/phd-research-support': typeof PhdResearchSupportRoute
  '/photoshop-academic-project-help': typeof PhotoshopAcademicProjectHelpRoute
  '/physical-project-models': typeof PhysicalProjectModelsRoute
  '/research-methodology-support': typeof ResearchMethodologySupportRoute
  '/research-proposal-support': typeof ResearchProposalSupportRoute
  '/revit-project-help': typeof RevitProjectHelpRoute
  '/science-academic-support': typeof ScienceAcademicSupportRoute
  '/social-science-academic-support': typeof SocialScienceAcademicSupportRoute
  '/spss-statistics-help': typeof SpssStatisticsHelpRoute
  '/thesis-dissertation-coaching': typeof ThesisDissertationCoachingRoute
  '/uk-academic-support': typeof UkAcademicSupportRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/locations/abu-dhabi': typeof LocationsAbuDhabiRoute
  '/locations/dubai': typeof LocationsDubaiRoute
  '/locations/lebanon': typeof LocationsLebanonRoute
  '/locations/montreal': typeof LocationsMontrealRoute
  '/locations/uk': typeof LocationsUkRoute
  '/resources/architecture-maquette-guide': typeof ResourcesArchitectureMaquetteGuideRoute
  '/resources/engineering-final-year-project-guide': typeof ResourcesEngineeringFinalYearProjectGuideRoute
  '/resources/how-to-choose-dissertation-methodology': typeof ResourcesHowToChooseDissertationMethodologyRoute
  '/resources/revit-for-architecture-students': typeof ResourcesRevitForArchitectureStudentsRoute
  '/resources/spss-dissertation-data-analysis-guide': typeof ResourcesSpssDissertationDataAnalysisGuideRoute
  '/services/academic-coaching': typeof ServicesAcademicCoachingRoute
  '/services/academic-writing-coaching': typeof ServicesAcademicWritingCoachingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/exam-preparation': typeof ServicesExamPreparationRoute
  '/services/research-methodology': typeof ServicesResearchMethodologyRoute
  '/services/research-statistics-support': typeof ServicesResearchStatisticsSupportRoute
  '/services/sat-preparation': typeof ServicesSatPreparationRoute
  '/services/thesis-dissertation-coaching': typeof ServicesThesisDissertationCoachingRoute
  '/services/university-tutoring': typeof ServicesUniversityTutoringRoute
  '/locations/': typeof LocationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-max-help': typeof R3dMaxHelpRoute
  '/3d-modelling-help': typeof R3dModellingHelpRoute
  '/about': typeof AboutRoute
  '/abu-dhabi-academic-support': typeof AbuDhabiAcademicSupportRoute
  '/academic-writing-coaching': typeof AcademicWritingCoachingRoute
  '/architecture-maquette-help': typeof ArchitectureMaquetteHelpRoute
  '/architecture-project-help': typeof ArchitectureProjectHelpRoute
  '/arduino-project-help': typeof ArduinoProjectHelpRoute
  '/arts-humanities-academic-support': typeof ArtsHumanitiesAcademicSupportRoute
  '/assignment-coursework-guidance': typeof AssignmentCourseworkGuidanceRoute
  '/autocad-help': typeof AutocadHelpRoute
  '/building-model-help': typeof BuildingModelHelpRoute
  '/business-academic-support': typeof BusinessAcademicSupportRoute
  '/capstone-project-support': typeof CapstoneProjectSupportRoute
  '/computer-science-academic-support': typeof ComputerScienceAcademicSupportRoute
  '/contact': typeof ContactRoute
  '/data-analysis-statistics': typeof DataAnalysisStatisticsRoute
  '/design-academic-support': typeof DesignAcademicSupportRoute
  '/dubai-academic-support': typeof DubaiAcademicSupportRoute
  '/engineering-project-help': typeof EngineeringProjectHelpRoute
  '/engineering-software-support': typeof EngineeringSoftwareSupportRoute
  '/final-year-project-support': typeof FinalYearProjectSupportRoute
  '/gis-project-help': typeof GisProjectHelpRoute
  '/international-student-academic-support': typeof InternationalStudentAcademicSupportRoute
  '/law-academic-support': typeof LawAcademicSupportRoute
  '/lebanon-academic-support': typeof LebanonAcademicSupportRoute
  '/literature-review-support': typeof LiteratureReviewSupportRoute
  '/medicine-academic-support': typeof MedicineAcademicSupportRoute
  '/montreal-academic-support': typeof MontrealAcademicSupportRoute
  '/phd-research-support': typeof PhdResearchSupportRoute
  '/photoshop-academic-project-help': typeof PhotoshopAcademicProjectHelpRoute
  '/physical-project-models': typeof PhysicalProjectModelsRoute
  '/research-methodology-support': typeof ResearchMethodologySupportRoute
  '/research-proposal-support': typeof ResearchProposalSupportRoute
  '/revit-project-help': typeof RevitProjectHelpRoute
  '/science-academic-support': typeof ScienceAcademicSupportRoute
  '/social-science-academic-support': typeof SocialScienceAcademicSupportRoute
  '/spss-statistics-help': typeof SpssStatisticsHelpRoute
  '/thesis-dissertation-coaching': typeof ThesisDissertationCoachingRoute
  '/uk-academic-support': typeof UkAcademicSupportRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/locations/abu-dhabi': typeof LocationsAbuDhabiRoute
  '/locations/dubai': typeof LocationsDubaiRoute
  '/locations/lebanon': typeof LocationsLebanonRoute
  '/locations/montreal': typeof LocationsMontrealRoute
  '/locations/uk': typeof LocationsUkRoute
  '/resources/architecture-maquette-guide': typeof ResourcesArchitectureMaquetteGuideRoute
  '/resources/engineering-final-year-project-guide': typeof ResourcesEngineeringFinalYearProjectGuideRoute
  '/resources/how-to-choose-dissertation-methodology': typeof ResourcesHowToChooseDissertationMethodologyRoute
  '/resources/revit-for-architecture-students': typeof ResourcesRevitForArchitectureStudentsRoute
  '/resources/spss-dissertation-data-analysis-guide': typeof ResourcesSpssDissertationDataAnalysisGuideRoute
  '/services/academic-coaching': typeof ServicesAcademicCoachingRoute
  '/services/academic-writing-coaching': typeof ServicesAcademicWritingCoachingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/exam-preparation': typeof ServicesExamPreparationRoute
  '/services/research-methodology': typeof ServicesResearchMethodologyRoute
  '/services/research-statistics-support': typeof ServicesResearchStatisticsSupportRoute
  '/services/sat-preparation': typeof ServicesSatPreparationRoute
  '/services/thesis-dissertation-coaching': typeof ServicesThesisDissertationCoachingRoute
  '/services/university-tutoring': typeof ServicesUniversityTutoringRoute
  '/locations': typeof LocationsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-max-help': typeof R3dMaxHelpRoute
  '/3d-modelling-help': typeof R3dModellingHelpRoute
  '/about': typeof AboutRoute
  '/abu-dhabi-academic-support': typeof AbuDhabiAcademicSupportRoute
  '/academic-writing-coaching': typeof AcademicWritingCoachingRoute
  '/architecture-maquette-help': typeof ArchitectureMaquetteHelpRoute
  '/architecture-project-help': typeof ArchitectureProjectHelpRoute
  '/arduino-project-help': typeof ArduinoProjectHelpRoute
  '/arts-humanities-academic-support': typeof ArtsHumanitiesAcademicSupportRoute
  '/assignment-coursework-guidance': typeof AssignmentCourseworkGuidanceRoute
  '/autocad-help': typeof AutocadHelpRoute
  '/building-model-help': typeof BuildingModelHelpRoute
  '/business-academic-support': typeof BusinessAcademicSupportRoute
  '/capstone-project-support': typeof CapstoneProjectSupportRoute
  '/computer-science-academic-support': typeof ComputerScienceAcademicSupportRoute
  '/contact': typeof ContactRoute
  '/data-analysis-statistics': typeof DataAnalysisStatisticsRoute
  '/design-academic-support': typeof DesignAcademicSupportRoute
  '/dubai-academic-support': typeof DubaiAcademicSupportRoute
  '/engineering-project-help': typeof EngineeringProjectHelpRoute
  '/engineering-software-support': typeof EngineeringSoftwareSupportRoute
  '/final-year-project-support': typeof FinalYearProjectSupportRoute
  '/gis-project-help': typeof GisProjectHelpRoute
  '/international-student-academic-support': typeof InternationalStudentAcademicSupportRoute
  '/law-academic-support': typeof LawAcademicSupportRoute
  '/lebanon-academic-support': typeof LebanonAcademicSupportRoute
  '/literature-review-support': typeof LiteratureReviewSupportRoute
  '/medicine-academic-support': typeof MedicineAcademicSupportRoute
  '/montreal-academic-support': typeof MontrealAcademicSupportRoute
  '/phd-research-support': typeof PhdResearchSupportRoute
  '/photoshop-academic-project-help': typeof PhotoshopAcademicProjectHelpRoute
  '/physical-project-models': typeof PhysicalProjectModelsRoute
  '/research-methodology-support': typeof ResearchMethodologySupportRoute
  '/research-proposal-support': typeof ResearchProposalSupportRoute
  '/revit-project-help': typeof RevitProjectHelpRoute
  '/science-academic-support': typeof ScienceAcademicSupportRoute
  '/social-science-academic-support': typeof SocialScienceAcademicSupportRoute
  '/spss-statistics-help': typeof SpssStatisticsHelpRoute
  '/thesis-dissertation-coaching': typeof ThesisDissertationCoachingRoute
  '/uk-academic-support': typeof UkAcademicSupportRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/locations/abu-dhabi': typeof LocationsAbuDhabiRoute
  '/locations/dubai': typeof LocationsDubaiRoute
  '/locations/lebanon': typeof LocationsLebanonRoute
  '/locations/montreal': typeof LocationsMontrealRoute
  '/locations/uk': typeof LocationsUkRoute
  '/resources/architecture-maquette-guide': typeof ResourcesArchitectureMaquetteGuideRoute
  '/resources/engineering-final-year-project-guide': typeof ResourcesEngineeringFinalYearProjectGuideRoute
  '/resources/how-to-choose-dissertation-methodology': typeof ResourcesHowToChooseDissertationMethodologyRoute
  '/resources/revit-for-architecture-students': typeof ResourcesRevitForArchitectureStudentsRoute
  '/resources/spss-dissertation-data-analysis-guide': typeof ResourcesSpssDissertationDataAnalysisGuideRoute
  '/services/academic-coaching': typeof ServicesAcademicCoachingRoute
  '/services/academic-writing-coaching': typeof ServicesAcademicWritingCoachingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/exam-preparation': typeof ServicesExamPreparationRoute
  '/services/research-methodology': typeof ServicesResearchMethodologyRoute
  '/services/research-statistics-support': typeof ServicesResearchStatisticsSupportRoute
  '/services/sat-preparation': typeof ServicesSatPreparationRoute
  '/services/thesis-dissertation-coaching': typeof ServicesThesisDissertationCoachingRoute
  '/services/university-tutoring': typeof ServicesUniversityTutoringRoute
  '/locations/': typeof LocationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-max-help'
    | '/3d-modelling-help'
    | '/about'
    | '/abu-dhabi-academic-support'
    | '/academic-writing-coaching'
    | '/architecture-maquette-help'
    | '/architecture-project-help'
    | '/arduino-project-help'
    | '/arts-humanities-academic-support'
    | '/assignment-coursework-guidance'
    | '/autocad-help'
    | '/building-model-help'
    | '/business-academic-support'
    | '/capstone-project-support'
    | '/computer-science-academic-support'
    | '/contact'
    | '/data-analysis-statistics'
    | '/design-academic-support'
    | '/dubai-academic-support'
    | '/engineering-project-help'
    | '/engineering-software-support'
    | '/final-year-project-support'
    | '/gis-project-help'
    | '/international-student-academic-support'
    | '/law-academic-support'
    | '/lebanon-academic-support'
    | '/literature-review-support'
    | '/medicine-academic-support'
    | '/montreal-academic-support'
    | '/phd-research-support'
    | '/photoshop-academic-project-help'
    | '/physical-project-models'
    | '/research-methodology-support'
    | '/research-proposal-support'
    | '/revit-project-help'
    | '/science-academic-support'
    | '/social-science-academic-support'
    | '/spss-statistics-help'
    | '/thesis-dissertation-coaching'
    | '/uk-academic-support'
    | '/who-we-help'
    | '/locations/abu-dhabi'
    | '/locations/dubai'
    | '/locations/lebanon'
    | '/locations/montreal'
    | '/locations/uk'
    | '/resources/architecture-maquette-guide'
    | '/resources/engineering-final-year-project-guide'
    | '/resources/how-to-choose-dissertation-methodology'
    | '/resources/revit-for-architecture-students'
    | '/resources/spss-dissertation-data-analysis-guide'
    | '/services/academic-coaching'
    | '/services/academic-writing-coaching'
    | '/services/editing-proofreading'
    | '/services/exam-preparation'
    | '/services/research-methodology'
    | '/services/research-statistics-support'
    | '/services/sat-preparation'
    | '/services/thesis-dissertation-coaching'
    | '/services/university-tutoring'
    | '/locations/'
    | '/resources/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-max-help'
    | '/3d-modelling-help'
    | '/about'
    | '/abu-dhabi-academic-support'
    | '/academic-writing-coaching'
    | '/architecture-maquette-help'
    | '/architecture-project-help'
    | '/arduino-project-help'
    | '/arts-humanities-academic-support'
    | '/assignment-coursework-guidance'
    | '/autocad-help'
    | '/building-model-help'
    | '/business-academic-support'
    | '/capstone-project-support'
    | '/computer-science-academic-support'
    | '/contact'
    | '/data-analysis-statistics'
    | '/design-academic-support'
    | '/dubai-academic-support'
    | '/engineering-project-help'
    | '/engineering-software-support'
    | '/final-year-project-support'
    | '/gis-project-help'
    | '/international-student-academic-support'
    | '/law-academic-support'
    | '/lebanon-academic-support'
    | '/literature-review-support'
    | '/medicine-academic-support'
    | '/montreal-academic-support'
    | '/phd-research-support'
    | '/photoshop-academic-project-help'
    | '/physical-project-models'
    | '/research-methodology-support'
    | '/research-proposal-support'
    | '/revit-project-help'
    | '/science-academic-support'
    | '/social-science-academic-support'
    | '/spss-statistics-help'
    | '/thesis-dissertation-coaching'
    | '/uk-academic-support'
    | '/who-we-help'
    | '/locations/abu-dhabi'
    | '/locations/dubai'
    | '/locations/lebanon'
    | '/locations/montreal'
    | '/locations/uk'
    | '/resources/architecture-maquette-guide'
    | '/resources/engineering-final-year-project-guide'
    | '/resources/how-to-choose-dissertation-methodology'
    | '/resources/revit-for-architecture-students'
    | '/resources/spss-dissertation-data-analysis-guide'
    | '/services/academic-coaching'
    | '/services/academic-writing-coaching'
    | '/services/editing-proofreading'
    | '/services/exam-preparation'
    | '/services/research-methodology'
    | '/services/research-statistics-support'
    | '/services/sat-preparation'
    | '/services/thesis-dissertation-coaching'
    | '/services/university-tutoring'
    | '/locations'
    | '/resources'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/3d-max-help'
    | '/3d-modelling-help'
    | '/about'
    | '/abu-dhabi-academic-support'
    | '/academic-writing-coaching'
    | '/architecture-maquette-help'
    | '/architecture-project-help'
    | '/arduino-project-help'
    | '/arts-humanities-academic-support'
    | '/assignment-coursework-guidance'
    | '/autocad-help'
    | '/building-model-help'
    | '/business-academic-support'
    | '/capstone-project-support'
    | '/computer-science-academic-support'
    | '/contact'
    | '/data-analysis-statistics'
    | '/design-academic-support'
    | '/dubai-academic-support'
    | '/engineering-project-help'
    | '/engineering-software-support'
    | '/final-year-project-support'
    | '/gis-project-help'
    | '/international-student-academic-support'
    | '/law-academic-support'
    | '/lebanon-academic-support'
    | '/literature-review-support'
    | '/medicine-academic-support'
    | '/montreal-academic-support'
    | '/phd-research-support'
    | '/photoshop-academic-project-help'
    | '/physical-project-models'
    | '/research-methodology-support'
    | '/research-proposal-support'
    | '/revit-project-help'
    | '/science-academic-support'
    | '/social-science-academic-support'
    | '/spss-statistics-help'
    | '/thesis-dissertation-coaching'
    | '/uk-academic-support'
    | '/who-we-help'
    | '/locations/abu-dhabi'
    | '/locations/dubai'
    | '/locations/lebanon'
    | '/locations/montreal'
    | '/locations/uk'
    | '/resources/architecture-maquette-guide'
    | '/resources/engineering-final-year-project-guide'
    | '/resources/how-to-choose-dissertation-methodology'
    | '/resources/revit-for-architecture-students'
    | '/resources/spss-dissertation-data-analysis-guide'
    | '/services/academic-coaching'
    | '/services/academic-writing-coaching'
    | '/services/editing-proofreading'
    | '/services/exam-preparation'
    | '/services/research-methodology'
    | '/services/research-statistics-support'
    | '/services/sat-preparation'
    | '/services/thesis-dissertation-coaching'
    | '/services/university-tutoring'
    | '/locations/'
    | '/resources/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dMaxHelpRoute: typeof R3dMaxHelpRoute
  R3dModellingHelpRoute: typeof R3dModellingHelpRoute
  AboutRoute: typeof AboutRoute
  AbuDhabiAcademicSupportRoute: typeof AbuDhabiAcademicSupportRoute
  AcademicWritingCoachingRoute: typeof AcademicWritingCoachingRoute
  ArchitectureMaquetteHelpRoute: typeof ArchitectureMaquetteHelpRoute
  ArchitectureProjectHelpRoute: typeof ArchitectureProjectHelpRoute
  ArduinoProjectHelpRoute: typeof ArduinoProjectHelpRoute
  ArtsHumanitiesAcademicSupportRoute: typeof ArtsHumanitiesAcademicSupportRoute
  AssignmentCourseworkGuidanceRoute: typeof AssignmentCourseworkGuidanceRoute
  AutocadHelpRoute: typeof AutocadHelpRoute
  BuildingModelHelpRoute: typeof BuildingModelHelpRoute
  BusinessAcademicSupportRoute: typeof BusinessAcademicSupportRoute
  CapstoneProjectSupportRoute: typeof CapstoneProjectSupportRoute
  ComputerScienceAcademicSupportRoute: typeof ComputerScienceAcademicSupportRoute
  ContactRoute: typeof ContactRoute
  DataAnalysisStatisticsRoute: typeof DataAnalysisStatisticsRoute
  DesignAcademicSupportRoute: typeof DesignAcademicSupportRoute
  DubaiAcademicSupportRoute: typeof DubaiAcademicSupportRoute
  EngineeringProjectHelpRoute: typeof EngineeringProjectHelpRoute
  EngineeringSoftwareSupportRoute: typeof EngineeringSoftwareSupportRoute
  FinalYearProjectSupportRoute: typeof FinalYearProjectSupportRoute
  GisProjectHelpRoute: typeof GisProjectHelpRoute
  InternationalStudentAcademicSupportRoute: typeof InternationalStudentAcademicSupportRoute
  LawAcademicSupportRoute: typeof LawAcademicSupportRoute
  LebanonAcademicSupportRoute: typeof LebanonAcademicSupportRoute
  LiteratureReviewSupportRoute: typeof LiteratureReviewSupportRoute
  MedicineAcademicSupportRoute: typeof MedicineAcademicSupportRoute
  MontrealAcademicSupportRoute: typeof MontrealAcademicSupportRoute
  PhdResearchSupportRoute: typeof PhdResearchSupportRoute
  PhotoshopAcademicProjectHelpRoute: typeof PhotoshopAcademicProjectHelpRoute
  PhysicalProjectModelsRoute: typeof PhysicalProjectModelsRoute
  ResearchMethodologySupportRoute: typeof ResearchMethodologySupportRoute
  ResearchProposalSupportRoute: typeof ResearchProposalSupportRoute
  RevitProjectHelpRoute: typeof RevitProjectHelpRoute
  ScienceAcademicSupportRoute: typeof ScienceAcademicSupportRoute
  SocialScienceAcademicSupportRoute: typeof SocialScienceAcademicSupportRoute
  SpssStatisticsHelpRoute: typeof SpssStatisticsHelpRoute
  ThesisDissertationCoachingRoute: typeof ThesisDissertationCoachingRoute
  UkAcademicSupportRoute: typeof UkAcademicSupportRoute
  WhoWeHelpRoute: typeof WhoWeHelpRoute
  LocationsAbuDhabiRoute: typeof LocationsAbuDhabiRoute
  LocationsDubaiRoute: typeof LocationsDubaiRoute
  LocationsLebanonRoute: typeof LocationsLebanonRoute
  LocationsMontrealRoute: typeof LocationsMontrealRoute
  LocationsUkRoute: typeof LocationsUkRoute
  ResourcesArchitectureMaquetteGuideRoute: typeof ResourcesArchitectureMaquetteGuideRoute
  ResourcesEngineeringFinalYearProjectGuideRoute: typeof ResourcesEngineeringFinalYearProjectGuideRoute
  ResourcesHowToChooseDissertationMethodologyRoute: typeof ResourcesHowToChooseDissertationMethodologyRoute
  ResourcesRevitForArchitectureStudentsRoute: typeof ResourcesRevitForArchitectureStudentsRoute
  ResourcesSpssDissertationDataAnalysisGuideRoute: typeof ResourcesSpssDissertationDataAnalysisGuideRoute
  ServicesAcademicCoachingRoute: typeof ServicesAcademicCoachingRoute
  ServicesAcademicWritingCoachingRoute: typeof ServicesAcademicWritingCoachingRoute
  ServicesEditingProofreadingRoute: typeof ServicesEditingProofreadingRoute
  ServicesExamPreparationRoute: typeof ServicesExamPreparationRoute
  ServicesResearchMethodologyRoute: typeof ServicesResearchMethodologyRoute
  ServicesResearchStatisticsSupportRoute: typeof ServicesResearchStatisticsSupportRoute
  ServicesSatPreparationRoute: typeof ServicesSatPreparationRoute
  ServicesThesisDissertationCoachingRoute: typeof ServicesThesisDissertationCoachingRoute
  ServicesUniversityTutoringRoute: typeof ServicesUniversityTutoringRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-max-help': {
      id: '/3d-max-help'
      path: '/3d-max-help'
      fullPath: '/3d-max-help'
      preLoaderRoute: typeof R3dMaxHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-modelling-help': {
      id: '/3d-modelling-help'
      path: '/3d-modelling-help'
      fullPath: '/3d-modelling-help'
      preLoaderRoute: typeof R3dModellingHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abu-dhabi-academic-support': {
      id: '/abu-dhabi-academic-support'
      path: '/abu-dhabi-academic-support'
      fullPath: '/abu-dhabi-academic-support'
      preLoaderRoute: typeof AbuDhabiAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-writing-coaching': {
      id: '/academic-writing-coaching'
      path: '/academic-writing-coaching'
      fullPath: '/academic-writing-coaching'
      preLoaderRoute: typeof AcademicWritingCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture-maquette-help': {
      id: '/architecture-maquette-help'
      path: '/architecture-maquette-help'
      fullPath: '/architecture-maquette-help'
      preLoaderRoute: typeof ArchitectureMaquetteHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture-project-help': {
      id: '/architecture-project-help'
      path: '/architecture-project-help'
      fullPath: '/architecture-project-help'
      preLoaderRoute: typeof ArchitectureProjectHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arduino-project-help': {
      id: '/arduino-project-help'
      path: '/arduino-project-help'
      fullPath: '/arduino-project-help'
      preLoaderRoute: typeof ArduinoProjectHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arts-humanities-academic-support': {
      id: '/arts-humanities-academic-support'
      path: '/arts-humanities-academic-support'
      fullPath: '/arts-humanities-academic-support'
      preLoaderRoute: typeof ArtsHumanitiesAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment-coursework-guidance': {
      id: '/assignment-coursework-guidance'
      path: '/assignment-coursework-guidance'
      fullPath: '/assignment-coursework-guidance'
      preLoaderRoute: typeof AssignmentCourseworkGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autocad-help': {
      id: '/autocad-help'
      path: '/autocad-help'
      fullPath: '/autocad-help'
      preLoaderRoute: typeof AutocadHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-model-help': {
      id: '/building-model-help'
      path: '/building-model-help'
      fullPath: '/building-model-help'
      preLoaderRoute: typeof BuildingModelHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-academic-support': {
      id: '/business-academic-support'
      path: '/business-academic-support'
      fullPath: '/business-academic-support'
      preLoaderRoute: typeof BusinessAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capstone-project-support': {
      id: '/capstone-project-support'
      path: '/capstone-project-support'
      fullPath: '/capstone-project-support'
      preLoaderRoute: typeof CapstoneProjectSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer-science-academic-support': {
      id: '/computer-science-academic-support'
      path: '/computer-science-academic-support'
      fullPath: '/computer-science-academic-support'
      preLoaderRoute: typeof ComputerScienceAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-analysis-statistics': {
      id: '/data-analysis-statistics'
      path: '/data-analysis-statistics'
      fullPath: '/data-analysis-statistics'
      preLoaderRoute: typeof DataAnalysisStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-academic-support': {
      id: '/design-academic-support'
      path: '/design-academic-support'
      fullPath: '/design-academic-support'
      preLoaderRoute: typeof DesignAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai-academic-support': {
      id: '/dubai-academic-support'
      path: '/dubai-academic-support'
      fullPath: '/dubai-academic-support'
      preLoaderRoute: typeof DubaiAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-project-help': {
      id: '/engineering-project-help'
      path: '/engineering-project-help'
      fullPath: '/engineering-project-help'
      preLoaderRoute: typeof EngineeringProjectHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-software-support': {
      id: '/engineering-software-support'
      path: '/engineering-software-support'
      fullPath: '/engineering-software-support'
      preLoaderRoute: typeof EngineeringSoftwareSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-year-project-support': {
      id: '/final-year-project-support'
      path: '/final-year-project-support'
      fullPath: '/final-year-project-support'
      preLoaderRoute: typeof FinalYearProjectSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-project-help': {
      id: '/gis-project-help'
      path: '/gis-project-help'
      fullPath: '/gis-project-help'
      preLoaderRoute: typeof GisProjectHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-student-academic-support': {
      id: '/international-student-academic-support'
      path: '/international-student-academic-support'
      fullPath: '/international-student-academic-support'
      preLoaderRoute: typeof InternationalStudentAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law-academic-support': {
      id: '/law-academic-support'
      path: '/law-academic-support'
      fullPath: '/law-academic-support'
      preLoaderRoute: typeof LawAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lebanon-academic-support': {
      id: '/lebanon-academic-support'
      path: '/lebanon-academic-support'
      fullPath: '/lebanon-academic-support'
      preLoaderRoute: typeof LebanonAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature-review-support': {
      id: '/literature-review-support'
      path: '/literature-review-support'
      fullPath: '/literature-review-support'
      preLoaderRoute: typeof LiteratureReviewSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine-academic-support': {
      id: '/medicine-academic-support'
      path: '/medicine-academic-support'
      fullPath: '/medicine-academic-support'
      preLoaderRoute: typeof MedicineAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montreal-academic-support': {
      id: '/montreal-academic-support'
      path: '/montreal-academic-support'
      fullPath: '/montreal-academic-support'
      preLoaderRoute: typeof MontrealAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phd-research-support': {
      id: '/phd-research-support'
      path: '/phd-research-support'
      fullPath: '/phd-research-support'
      preLoaderRoute: typeof PhdResearchSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photoshop-academic-project-help': {
      id: '/photoshop-academic-project-help'
      path: '/photoshop-academic-project-help'
      fullPath: '/photoshop-academic-project-help'
      preLoaderRoute: typeof PhotoshopAcademicProjectHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-project-models': {
      id: '/physical-project-models'
      path: '/physical-project-models'
      fullPath: '/physical-project-models'
      preLoaderRoute: typeof PhysicalProjectModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-methodology-support': {
      id: '/research-methodology-support'
      path: '/research-methodology-support'
      fullPath: '/research-methodology-support'
      preLoaderRoute: typeof ResearchMethodologySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-proposal-support': {
      id: '/research-proposal-support'
      path: '/research-proposal-support'
      fullPath: '/research-proposal-support'
      preLoaderRoute: typeof ResearchProposalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revit-project-help': {
      id: '/revit-project-help'
      path: '/revit-project-help'
      fullPath: '/revit-project-help'
      preLoaderRoute: typeof RevitProjectHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science-academic-support': {
      id: '/science-academic-support'
      path: '/science-academic-support'
      fullPath: '/science-academic-support'
      preLoaderRoute: typeof ScienceAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-science-academic-support': {
      id: '/social-science-academic-support'
      path: '/social-science-academic-support'
      fullPath: '/social-science-academic-support'
      preLoaderRoute: typeof SocialScienceAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spss-statistics-help': {
      id: '/spss-statistics-help'
      path: '/spss-statistics-help'
      fullPath: '/spss-statistics-help'
      preLoaderRoute: typeof SpssStatisticsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thesis-dissertation-coaching': {
      id: '/thesis-dissertation-coaching'
      path: '/thesis-dissertation-coaching'
      fullPath: '/thesis-dissertation-coaching'
      preLoaderRoute: typeof ThesisDissertationCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk-academic-support': {
      id: '/uk-academic-support'
      path: '/uk-academic-support'
      fullPath: '/uk-academic-support'
      preLoaderRoute: typeof UkAcademicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help': {
      id: '/who-we-help'
      path: '/who-we-help'
      fullPath: '/who-we-help'
      preLoaderRoute: typeof WhoWeHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/abu-dhabi': {
      id: '/locations/abu-dhabi'
      path: '/locations/abu-dhabi'
      fullPath: '/locations/abu-dhabi'
      preLoaderRoute: typeof LocationsAbuDhabiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/dubai': {
      id: '/locations/dubai'
      path: '/locations/dubai'
      fullPath: '/locations/dubai'
      preLoaderRoute: typeof LocationsDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/lebanon': {
      id: '/locations/lebanon'
      path: '/locations/lebanon'
      fullPath: '/locations/lebanon'
      preLoaderRoute: typeof LocationsLebanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/montreal': {
      id: '/locations/montreal'
      path: '/locations/montreal'
      fullPath: '/locations/montreal'
      preLoaderRoute: typeof LocationsMontrealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/uk': {
      id: '/locations/uk'
      path: '/locations/uk'
      fullPath: '/locations/uk'
      preLoaderRoute: typeof LocationsUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/architecture-maquette-guide': {
      id: '/resources/architecture-maquette-guide'
      path: '/resources/architecture-maquette-guide'
      fullPath: '/resources/architecture-maquette-guide'
      preLoaderRoute: typeof ResourcesArchitectureMaquetteGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/engineering-final-year-project-guide': {
      id: '/resources/engineering-final-year-project-guide'
      path: '/resources/engineering-final-year-project-guide'
      fullPath: '/resources/engineering-final-year-project-guide'
      preLoaderRoute: typeof ResourcesEngineeringFinalYearProjectGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/how-to-choose-dissertation-methodology': {
      id: '/resources/how-to-choose-dissertation-methodology'
      path: '/resources/how-to-choose-dissertation-methodology'
      fullPath: '/resources/how-to-choose-dissertation-methodology'
      preLoaderRoute: typeof ResourcesHowToChooseDissertationMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/revit-for-architecture-students': {
      id: '/resources/revit-for-architecture-students'
      path: '/resources/revit-for-architecture-students'
      fullPath: '/resources/revit-for-architecture-students'
      preLoaderRoute: typeof ResourcesRevitForArchitectureStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/spss-dissertation-data-analysis-guide': {
      id: '/resources/spss-dissertation-data-analysis-guide'
      path: '/resources/spss-dissertation-data-analysis-guide'
      fullPath: '/resources/spss-dissertation-data-analysis-guide'
      preLoaderRoute: typeof ResourcesSpssDissertationDataAnalysisGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/academic-coaching': {
      id: '/services/academic-coaching'
      path: '/services/academic-coaching'
      fullPath: '/services/academic-coaching'
      preLoaderRoute: typeof ServicesAcademicCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/academic-writing-coaching': {
      id: '/services/academic-writing-coaching'
      path: '/services/academic-writing-coaching'
      fullPath: '/services/academic-writing-coaching'
      preLoaderRoute: typeof ServicesAcademicWritingCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/editing-proofreading': {
      id: '/services/editing-proofreading'
      path: '/services/editing-proofreading'
      fullPath: '/services/editing-proofreading'
      preLoaderRoute: typeof ServicesEditingProofreadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/exam-preparation': {
      id: '/services/exam-preparation'
      path: '/services/exam-preparation'
      fullPath: '/services/exam-preparation'
      preLoaderRoute: typeof ServicesExamPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research-methodology': {
      id: '/services/research-methodology'
      path: '/services/research-methodology'
      fullPath: '/services/research-methodology'
      preLoaderRoute: typeof ServicesResearchMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research-statistics-support': {
      id: '/services/research-statistics-support'
      path: '/services/research-statistics-support'
      fullPath: '/services/research-statistics-support'
      preLoaderRoute: typeof ServicesResearchStatisticsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sat-preparation': {
      id: '/services/sat-preparation'
      path: '/services/sat-preparation'
      fullPath: '/services/sat-preparation'
      preLoaderRoute: typeof ServicesSatPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/thesis-dissertation-coaching': {
      id: '/services/thesis-dissertation-coaching'
      path: '/services/thesis-dissertation-coaching'
      fullPath: '/services/thesis-dissertation-coaching'
      preLoaderRoute: typeof ServicesThesisDissertationCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/university-tutoring': {
      id: '/services/university-tutoring'
      path: '/services/university-tutoring'
      fullPath: '/services/university-tutoring'
      preLoaderRoute: typeof ServicesUniversityTutoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dMaxHelpRoute: R3dMaxHelpRoute,
  R3dModellingHelpRoute: R3dModellingHelpRoute,
  AboutRoute: AboutRoute,
  AbuDhabiAcademicSupportRoute: AbuDhabiAcademicSupportRoute,
  AcademicWritingCoachingRoute: AcademicWritingCoachingRoute,
  ArchitectureMaquetteHelpRoute: ArchitectureMaquetteHelpRoute,
  ArchitectureProjectHelpRoute: ArchitectureProjectHelpRoute,
  ArduinoProjectHelpRoute: ArduinoProjectHelpRoute,
  ArtsHumanitiesAcademicSupportRoute: ArtsHumanitiesAcademicSupportRoute,
  AssignmentCourseworkGuidanceRoute: AssignmentCourseworkGuidanceRoute,
  AutocadHelpRoute: AutocadHelpRoute,
  BuildingModelHelpRoute: BuildingModelHelpRoute,
  BusinessAcademicSupportRoute: BusinessAcademicSupportRoute,
  CapstoneProjectSupportRoute: CapstoneProjectSupportRoute,
  ComputerScienceAcademicSupportRoute: ComputerScienceAcademicSupportRoute,
  ContactRoute: ContactRoute,
  DataAnalysisStatisticsRoute: DataAnalysisStatisticsRoute,
  DesignAcademicSupportRoute: DesignAcademicSupportRoute,
  DubaiAcademicSupportRoute: DubaiAcademicSupportRoute,
  EngineeringProjectHelpRoute: EngineeringProjectHelpRoute,
  EngineeringSoftwareSupportRoute: EngineeringSoftwareSupportRoute,
  FinalYearProjectSupportRoute: FinalYearProjectSupportRoute,
  GisProjectHelpRoute: GisProjectHelpRoute,
  InternationalStudentAcademicSupportRoute:
    InternationalStudentAcademicSupportRoute,
  LawAcademicSupportRoute: LawAcademicSupportRoute,
  LebanonAcademicSupportRoute: LebanonAcademicSupportRoute,
  LiteratureReviewSupportRoute: LiteratureReviewSupportRoute,
  MedicineAcademicSupportRoute: MedicineAcademicSupportRoute,
  MontrealAcademicSupportRoute: MontrealAcademicSupportRoute,
  PhdResearchSupportRoute: PhdResearchSupportRoute,
  PhotoshopAcademicProjectHelpRoute: PhotoshopAcademicProjectHelpRoute,
  PhysicalProjectModelsRoute: PhysicalProjectModelsRoute,
  ResearchMethodologySupportRoute: ResearchMethodologySupportRoute,
  ResearchProposalSupportRoute: ResearchProposalSupportRoute,
  RevitProjectHelpRoute: RevitProjectHelpRoute,
  ScienceAcademicSupportRoute: ScienceAcademicSupportRoute,
  SocialScienceAcademicSupportRoute: SocialScienceAcademicSupportRoute,
  SpssStatisticsHelpRoute: SpssStatisticsHelpRoute,
  ThesisDissertationCoachingRoute: ThesisDissertationCoachingRoute,
  UkAcademicSupportRoute: UkAcademicSupportRoute,
  WhoWeHelpRoute: WhoWeHelpRoute,
  LocationsAbuDhabiRoute: LocationsAbuDhabiRoute,
  LocationsDubaiRoute: LocationsDubaiRoute,
  LocationsLebanonRoute: LocationsLebanonRoute,
  LocationsMontrealRoute: LocationsMontrealRoute,
  LocationsUkRoute: LocationsUkRoute,
  ResourcesArchitectureMaquetteGuideRoute:
    ResourcesArchitectureMaquetteGuideRoute,
  ResourcesEngineeringFinalYearProjectGuideRoute:
    ResourcesEngineeringFinalYearProjectGuideRoute,
  ResourcesHowToChooseDissertationMethodologyRoute:
    ResourcesHowToChooseDissertationMethodologyRoute,
  ResourcesRevitForArchitectureStudentsRoute:
    ResourcesRevitForArchitectureStudentsRoute,
  ResourcesSpssDissertationDataAnalysisGuideRoute:
    ResourcesSpssDissertationDataAnalysisGuideRoute,
  ServicesAcademicCoachingRoute: ServicesAcademicCoachingRoute,
  ServicesAcademicWritingCoachingRoute: ServicesAcademicWritingCoachingRoute,
  ServicesEditingProofreadingRoute: ServicesEditingProofreadingRoute,
  ServicesExamPreparationRoute: ServicesExamPreparationRoute,
  ServicesResearchMethodologyRoute: ServicesResearchMethodologyRoute,
  ServicesResearchStatisticsSupportRoute:
    ServicesResearchStatisticsSupportRoute,
  ServicesSatPreparationRoute: ServicesSatPreparationRoute,
  ServicesThesisDissertationCoachingRoute:
    ServicesThesisDissertationCoachingRoute,
  ServicesUniversityTutoringRoute: ServicesUniversityTutoringRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
