/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as WhoWeHelpRouteImport } from './routes/who-we-help'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsAbuDhabiRouteImport } from './routes/locations/abu-dhabi'
import { Route as LocationsDubaiRouteImport } from './routes/locations/dubai'
import { Route as LocationsLebanonRouteImport } from './routes/locations/lebanon'
import { Route as LocationsMontrealRouteImport } from './routes/locations/montreal'
import { Route as LocationsUkRouteImport } from './routes/locations/uk'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAcademicCoachingRouteImport } from './routes/services/academic-coaching'
import { Route as ServicesAcademicWritingCoachingRouteImport } from './routes/services/academic-writing-coaching'
import { Route as ServicesEditingProofreadingRouteImport } from './routes/services/editing-proofreading'
import { Route as ServicesExamPreparationRouteImport } from './routes/services/exam-preparation'
import { Route as ServicesResearchMethodologyRouteImport } from './routes/services/research-methodology'
import { Route as ServicesResearchStatisticsSupportRouteImport } from './routes/services/research-statistics-support'
import { Route as ServicesSatPreparationRouteImport } from './routes/services/sat-preparation'
import { Route as ServicesThesisDissertationCoachingRouteImport } from './routes/services/thesis-dissertation-coaching'
import { Route as ServicesUniversityTutoringRouteImport } from './routes/services/university-tutoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpRoute = WhoWeHelpRouteImport.update({
  id: '/who-we-help',
  path: '/who-we-help',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsAbuDhabiRoute = LocationsAbuDhabiRouteImport.update({
  id: '/locations/abu-dhabi',
  path: '/locations/abu-dhabi',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsDubaiRoute = LocationsDubaiRouteImport.update({
  id: '/locations/dubai',
  path: '/locations/dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLebanonRoute = LocationsLebanonRouteImport.update({
  id: '/locations/lebanon',
  path: '/locations/lebanon',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsMontrealRoute = LocationsMontrealRouteImport.update({
  id: '/locations/montreal',
  path: '/locations/montreal',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsUkRoute = LocationsUkRouteImport.update({
  id: '/locations/uk',
  path: '/locations/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAcademicCoachingRoute =
  ServicesAcademicCoachingRouteImport.update({
    id: '/services/academic-coaching',
    path: '/services/academic-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAcademicWritingCoachingRoute =
  ServicesAcademicWritingCoachingRouteImport.update({
    id: '/services/academic-writing-coaching',
    path: '/services/academic-writing-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEditingProofreadingRoute =
  ServicesEditingProofreadingRouteImport.update({
    id: '/services/editing-proofreading',
    path: '/services/editing-proofreading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesExamPreparationRoute = ServicesExamPreparationRouteImport.update({
  id: '/services/exam-preparation',
  path: '/services/exam-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResearchMethodologyRoute =
  ServicesResearchMethodologyRouteImport.update({
    id: '/services/research-methodology',
    path: '/services/research-methodology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesResearchStatisticsSupportRoute =
  ServicesResearchStatisticsSupportRouteImport.update({
    id: '/services/research-statistics-support',
    path: '/services/research-statistics-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSatPreparationRoute = ServicesSatPreparationRouteImport.update({
  id: '/services/sat-preparation',
  path: '/services/sat-preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesThesisDissertationCoachingRoute =
  ServicesThesisDissertationCoachingRouteImport.update({
    id: '/services/thesis-dissertation-coaching',
    path: '/services/thesis-dissertation-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUniversityTutoringRoute =
  ServicesUniversityTutoringRouteImport.update({
    id: '/services/university-tutoring',
    path: '/services/university-tutoring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/locations/abu-dhabi': typeof LocationsAbuDhabiRoute
  '/locations/dubai': typeof LocationsDubaiRoute
  '/locations/lebanon': typeof LocationsLebanonRoute
  '/locations/montreal': typeof LocationsMontrealRoute
  '/locations/uk': typeof LocationsUkRoute
  '/services/academic-coaching': typeof ServicesAcademicCoachingRoute
  '/services/academic-writing-coaching': typeof ServicesAcademicWritingCoachingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/exam-preparation': typeof ServicesExamPreparationRoute
  '/services/research-methodology': typeof ServicesResearchMethodologyRoute
  '/services/research-statistics-support': typeof ServicesResearchStatisticsSupportRoute
  '/services/sat-preparation': typeof ServicesSatPreparationRoute
  '/services/thesis-dissertation-coaching': typeof ServicesThesisDissertationCoachingRoute
  '/services/university-tutoring': typeof ServicesUniversityTutoringRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/locations/abu-dhabi': typeof LocationsAbuDhabiRoute
  '/locations/dubai': typeof LocationsDubaiRoute
  '/locations/lebanon': typeof LocationsLebanonRoute
  '/locations/montreal': typeof LocationsMontrealRoute
  '/locations/uk': typeof LocationsUkRoute
  '/services/academic-coaching': typeof ServicesAcademicCoachingRoute
  '/services/academic-writing-coaching': typeof ServicesAcademicWritingCoachingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/exam-preparation': typeof ServicesExamPreparationRoute
  '/services/research-methodology': typeof ServicesResearchMethodologyRoute
  '/services/research-statistics-support': typeof ServicesResearchStatisticsSupportRoute
  '/services/sat-preparation': typeof ServicesSatPreparationRoute
  '/services/thesis-dissertation-coaching': typeof ServicesThesisDissertationCoachingRoute
  '/services/university-tutoring': typeof ServicesUniversityTutoringRoute
  '/locations': typeof LocationsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/who-we-help': typeof WhoWeHelpRoute
  '/locations/abu-dhabi': typeof LocationsAbuDhabiRoute
  '/locations/dubai': typeof LocationsDubaiRoute
  '/locations/lebanon': typeof LocationsLebanonRoute
  '/locations/montreal': typeof LocationsMontrealRoute
  '/locations/uk': typeof LocationsUkRoute
  '/services/academic-coaching': typeof ServicesAcademicCoachingRoute
  '/services/academic-writing-coaching': typeof ServicesAcademicWritingCoachingRoute
  '/services/editing-proofreading': typeof ServicesEditingProofreadingRoute
  '/services/exam-preparation': typeof ServicesExamPreparationRoute
  '/services/research-methodology': typeof ServicesResearchMethodologyRoute
  '/services/research-statistics-support': typeof ServicesResearchStatisticsSupportRoute
  '/services/sat-preparation': typeof ServicesSatPreparationRoute
  '/services/thesis-dissertation-coaching': typeof ServicesThesisDissertationCoachingRoute
  '/services/university-tutoring': typeof ServicesUniversityTutoringRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/resources'
    | '/who-we-help'
    | '/locations/abu-dhabi'
    | '/locations/dubai'
    | '/locations/lebanon'
    | '/locations/montreal'
    | '/locations/uk'
    | '/services/academic-coaching'
    | '/services/academic-writing-coaching'
    | '/services/editing-proofreading'
    | '/services/exam-preparation'
    | '/services/research-methodology'
    | '/services/research-statistics-support'
    | '/services/sat-preparation'
    | '/services/thesis-dissertation-coaching'
    | '/services/university-tutoring'
    | '/locations/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/resources'
    | '/who-we-help'
    | '/locations/abu-dhabi'
    | '/locations/dubai'
    | '/locations/lebanon'
    | '/locations/montreal'
    | '/locations/uk'
    | '/services/academic-coaching'
    | '/services/academic-writing-coaching'
    | '/services/editing-proofreading'
    | '/services/exam-preparation'
    | '/services/research-methodology'
    | '/services/research-statistics-support'
    | '/services/sat-preparation'
    | '/services/thesis-dissertation-coaching'
    | '/services/university-tutoring'
    | '/locations'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/resources'
    | '/who-we-help'
    | '/locations/abu-dhabi'
    | '/locations/dubai'
    | '/locations/lebanon'
    | '/locations/montreal'
    | '/locations/uk'
    | '/services/academic-coaching'
    | '/services/academic-writing-coaching'
    | '/services/editing-proofreading'
    | '/services/exam-preparation'
    | '/services/research-methodology'
    | '/services/research-statistics-support'
    | '/services/sat-preparation'
    | '/services/thesis-dissertation-coaching'
    | '/services/university-tutoring'
    | '/locations/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ResourcesRoute: typeof ResourcesRoute
  WhoWeHelpRoute: typeof WhoWeHelpRoute
  LocationsAbuDhabiRoute: typeof LocationsAbuDhabiRoute
  LocationsDubaiRoute: typeof LocationsDubaiRoute
  LocationsLebanonRoute: typeof LocationsLebanonRoute
  LocationsMontrealRoute: typeof LocationsMontrealRoute
  LocationsUkRoute: typeof LocationsUkRoute
  ServicesAcademicCoachingRoute: typeof ServicesAcademicCoachingRoute
  ServicesAcademicWritingCoachingRoute: typeof ServicesAcademicWritingCoachingRoute
  ServicesEditingProofreadingRoute: typeof ServicesEditingProofreadingRoute
  ServicesExamPreparationRoute: typeof ServicesExamPreparationRoute
  ServicesResearchMethodologyRoute: typeof ServicesResearchMethodologyRoute
  ServicesResearchStatisticsSupportRoute: typeof ServicesResearchStatisticsSupportRoute
  ServicesSatPreparationRoute: typeof ServicesSatPreparationRoute
  ServicesThesisDissertationCoachingRoute: typeof ServicesThesisDissertationCoachingRoute
  ServicesUniversityTutoringRoute: typeof ServicesUniversityTutoringRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help': {
      id: '/who-we-help'
      path: '/who-we-help'
      fullPath: '/who-we-help'
      preLoaderRoute: typeof WhoWeHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/abu-dhabi': {
      id: '/locations/abu-dhabi'
      path: '/locations/abu-dhabi'
      fullPath: '/locations/abu-dhabi'
      preLoaderRoute: typeof LocationsAbuDhabiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/dubai': {
      id: '/locations/dubai'
      path: '/locations/dubai'
      fullPath: '/locations/dubai'
      preLoaderRoute: typeof LocationsDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/lebanon': {
      id: '/locations/lebanon'
      path: '/locations/lebanon'
      fullPath: '/locations/lebanon'
      preLoaderRoute: typeof LocationsLebanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/montreal': {
      id: '/locations/montreal'
      path: '/locations/montreal'
      fullPath: '/locations/montreal'
      preLoaderRoute: typeof LocationsMontrealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/uk': {
      id: '/locations/uk'
      path: '/locations/uk'
      fullPath: '/locations/uk'
      preLoaderRoute: typeof LocationsUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/academic-coaching': {
      id: '/services/academic-coaching'
      path: '/services/academic-coaching'
      fullPath: '/services/academic-coaching'
      preLoaderRoute: typeof ServicesAcademicCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/academic-writing-coaching': {
      id: '/services/academic-writing-coaching'
      path: '/services/academic-writing-coaching'
      fullPath: '/services/academic-writing-coaching'
      preLoaderRoute: typeof ServicesAcademicWritingCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/editing-proofreading': {
      id: '/services/editing-proofreading'
      path: '/services/editing-proofreading'
      fullPath: '/services/editing-proofreading'
      preLoaderRoute: typeof ServicesEditingProofreadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/exam-preparation': {
      id: '/services/exam-preparation'
      path: '/services/exam-preparation'
      fullPath: '/services/exam-preparation'
      preLoaderRoute: typeof ServicesExamPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research-methodology': {
      id: '/services/research-methodology'
      path: '/services/research-methodology'
      fullPath: '/services/research-methodology'
      preLoaderRoute: typeof ServicesResearchMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research-statistics-support': {
      id: '/services/research-statistics-support'
      path: '/services/research-statistics-support'
      fullPath: '/services/research-statistics-support'
      preLoaderRoute: typeof ServicesResearchStatisticsSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sat-preparation': {
      id: '/services/sat-preparation'
      path: '/services/sat-preparation'
      fullPath: '/services/sat-preparation'
      preLoaderRoute: typeof ServicesSatPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/thesis-dissertation-coaching': {
      id: '/services/thesis-dissertation-coaching'
      path: '/services/thesis-dissertation-coaching'
      fullPath: '/services/thesis-dissertation-coaching'
      preLoaderRoute: typeof ServicesThesisDissertationCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/university-tutoring': {
      id: '/services/university-tutoring'
      path: '/services/university-tutoring'
      fullPath: '/services/university-tutoring'
      preLoaderRoute: typeof ServicesUniversityTutoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ResourcesRoute: ResourcesRoute,
  WhoWeHelpRoute: WhoWeHelpRoute,
  LocationsAbuDhabiRoute: LocationsAbuDhabiRoute,
  LocationsDubaiRoute: LocationsDubaiRoute,
  LocationsLebanonRoute: LocationsLebanonRoute,
  LocationsMontrealRoute: LocationsMontrealRoute,
  LocationsUkRoute: LocationsUkRoute,
  ServicesAcademicCoachingRoute: ServicesAcademicCoachingRoute,
  ServicesAcademicWritingCoachingRoute: ServicesAcademicWritingCoachingRoute,
  ServicesEditingProofreadingRoute: ServicesEditingProofreadingRoute,
  ServicesExamPreparationRoute: ServicesExamPreparationRoute,
  ServicesResearchMethodologyRoute: ServicesResearchMethodologyRoute,
  ServicesResearchStatisticsSupportRoute:
    ServicesResearchStatisticsSupportRoute,
  ServicesSatPreparationRoute: ServicesSatPreparationRoute,
  ServicesThesisDissertationCoachingRoute:
    ServicesThesisDissertationCoachingRoute,
  ServicesUniversityTutoringRoute: ServicesUniversityTutoringRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
